### ISSUE TITLE
ModuleNotFoundError:No module named 'torch_scatter.scatter_cuda' 

### ISSUE THREAD

**Issue by dddyx** [NetworkScienceLab/GDM#1]
Hi! Thanks for your great job : )
I am having some problems reproducing your paper as instructed.
My running environment is:
```
Ubuntu 20.04
driver version: 465.31
torch.__version__: 1.0.1.post2
torch.cuda.is_available(): True
torch.version.cuda:9.0.176
```
When running this code:
`python network_dismantling/machine_learning/pytorch/reproduce_results.py --help`

there is an error displayed:
```
Traceback (most recent call last):
  File "network_dismantling/machine_learning/pytorch/reproduce_results.py", line 33, in <module>
    from network_dismantling.machine_learning.pytorch.grid import init_network_provider
  File "/home/dddx/NetworkDismantlingML/GDM/network_dismantling/machine_learning/pytorch/grid.py", line 33, in <module>
    from network_dismantling.machine_learning.pytorch.models.GAT import GAT_Model
  File "/home/dddx/NetworkDismantlingML/GDM/network_dismantling/machine_learning/pytorch/models/GAT.py", line 26, in <module>
    from torch_geometric.nn import GATConv
  File "/home/dddx/anaconda3/envs/gdm/lib/python3.7/site-packages/torch_geometric/nn/__init__.py", line 2, in <module>
    from .data_parallel import DataParallel
  File "/home/dddx/anaconda3/envs/gdm/lib/python3.7/site-packages/torch_geometric/nn/data_parallel.py", line 4, in <module>
    from torch_geometric.data import Batch
  File "/home/dddx/anaconda3/envs/gdm/lib/python3.7/site-packages/torch_geometric/data/__init__.py", line 1, in <module>
    from .data import Data
  File "/home/dddx/anaconda3/envs/gdm/lib/python3.7/site-packages/torch_geometric/data/data.py", line 4, in <module>
    from torch_geometric.utils import (contains_isolated_nodes,
  File "/home/dddx/anaconda3/envs/gdm/lib/python3.7/site-packages/torch_geometric/utils/__init__.py", line 2, in <module>
    from .scatter import scatter_
  File "/home/dddx/anaconda3/envs/gdm/lib/python3.7/site-packages/torch_geometric/utils/scatter.py", line 1, in <module>
    import torch_scatter
  File "/home/dddx/anaconda3/envs/gdm/lib/python3.7/site-packages/torch_scatter/__init__.py", line 3, in <module>
    from .mul import scatter_mul
  File "/home/dddx/anaconda3/envs/gdm/lib/python3.7/site-packages/torch_scatter/mul.py", line 3, in <module>
    from torch_scatter.utils.ext import get_func
  File "/home/dddx/anaconda3/envs/gdm/lib/python3.7/site-packages/torch_scatter/utils/ext.py", line 5, in <module>
    import torch_scatter.scatter_cuda
ModuleNotFoundError: No module named 'torch_scatter.scatter_cuda'

```
I would like to ask how this should be solved.

**Comment by eMarco** [comment]
Hi!
Looks like an issue with the installation of pytorch geometric's packages to me.
Can you try reinstalling them?

Googling a bit I found this issue, maybe it can help: https://github.com/pyg-team/pytorch_geometric/issues/478
